spring:
  datasource:
    url: jdbc:clickhouse:http://localhost:8123
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
    database: tutorial
    username: default
    password:
  hikari:
    connection-timeout: 2000
    maximum-pool-size: 5

  jpa:
    hibernate:
      #            ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    show-sql: true
    #properties:
      #hibernate.allow_update_outside_transaction: true
      #Are transactions required? Since Hibernate bulk insert wouldn't work (driver doesn't support them)
      # support by Clickhouse is really limited: "INSERT into one partition in one table of MergeTree family up to max_insert_size rows is transactional (ACID)"
    properties:
      hibernate:
        order_inserts: true
        jdbc:
          batch_size: 100
        #  order_inserts: true
        order_updates: true
        generate_statistics: true

logging:
  level:
    com.example.hellospring: debug
  file:
    path: hello-spring/logs
  config: classpath:logback-spring.xml

springdoc:
  api-docs:
    path: /open-api-docs
  swagger-ui:
    path: /swagger/index.html
    operations-sorter: method